#!/usr/bin/env bash

if [ "$#" -ne 2 ]; then
  printf "ERROR: Invalid arguments passed to hashed_run_test.sh\n" >&2
  printf "USAGE: hashed_run_test.sh <progam> <test_name>\n" >&2
  exit 1
fi

prog="$1"
test_name="$2"

SCRIPT_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

if [ ! -f "$SCRIPT_DIR/tests/${test_name}.stdin" ]; then
  printf "ERROR: MISSING .stdin FILE\n" >&2
  exit 1
fi

if [ ! -f "$SCRIPT_DIR/tests/${test_name}.n" ]; then
  printf "ERROR: MISSING .n FILE\n" >&2
  exit 1
fi

# Read the exact text into $n
IFS= read -r -d '' n < "$SCRIPT_DIR/tests/${test_name}.n"

# Note - `set -o pipefail` is used here to exit with error code generated by `prog` and to report it as $?.
hash=$(set -o pipefail; "$prog" "$n" < "$SCRIPT_DIR/tests/${test_name}.stdin" 2>/dev/null | "$SCRIPT_DIR/calc_hash")

exit_code=$?

if [[ $exit_code == 0 ]]; then
  printf "%s" "$hash"
elif [[ $exit_code != 1 ]]; then
  printf "WRONG EXIT CODE :D"
else
  printf "ERROR."
fi